name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: geeklink
  PORT: 8080
  GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_REGION: us-west1
  IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/geeklink:${{ github.sha }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ env.GCP_REGION }}
          gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars SUPABASE_URL=${{ env.SUPABASE_URL }},SUPABASE_KEY=${{ env.SUPABASE_KEY }},DATABASE_URL=${{ env.DATABASE_URL }},DIRECT_URL=${{ env.DIRECT_URL }} \
